In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import sys
sys.path.append('../')
from cython_folder.cTTM.cttm import CTTM

In [2]:
# 人工データ
N_tdv = [
    [
        [1, 2, 1, 2],
        [3, 2, 0, 1],
        [0, 2, 1, 0]
    ],
    [
        [1, 1, 1, 1],
        [3, 2, 1, 2],
        [0, 2, 1, 0]
    ],
    [
        [0, 0, 0, 0],
        [3, 2, 0, 1],
        [0, 2, 1, 0]
    ],
    [
        [1, 1, 1, 1],
        [3, 2, 1, 2],
        [0, 2, 1, 0]
    ],
    [
        [1, 2, 1, 2],
        [3, 2, 0, 1],
        [0, 2, 1, 0]
    ],
    [
        [1, 1, 1, 1],
        [3, 2, 1, 2],
        [0, 2, 1, 0]
    ],
    [
        [1, 2, 1, 2],
        [3, 2, 0, 1],
        [0, 2, 1, 0]
    ],
    [
        [1, 1, 1, 1],
        [3, 2, 1, 2],
        [0, 2, 1, 0]
    ],
    [
        [1, 2, 1, 2],
        [3, 2, 0, 1],
        [0, 2, 1, 0]
    ],
    [
        [1, 1, 1, 1],
        [3, 2, 1, 2],
        [0, 2, 1, 0]
    ]
]

In [3]:
# 人工データ: 補助情報集合
Sex_ds = [
    [0, 1, 0],
    [0, 0, 1],
    [0, 1, 1]
]

Con_ds = [
    [1, 3, 25],
    [1, 4, 15],
    [2, 3, 17]
]

In [4]:
# 学習
# k: トピック数, L: 依存時間数, N_tdv: 時刻・ユーザー毎のBOW行列, 
cttm = CTTM(K=5, L=3, V=4, S=3, N_tdv=N_tdv, Sex_ds=Sex_ds, Con_ds=Con_ds)
# ttm_estimateの引数: 反復数
cttm.cttm_estimate(10)

100%|██████████| 10/10 [00:00<00:00, 311.49it/s]


In [11]:
np.array(cttm.psi_pre_tks[0])

array([[0.02105722, 0.02105722, 0.02105722, 0.02105722, 0.02105722,
        0.02105722, 0.02105722, 0.02105722, 0.02105722, 0.02105722,
        0.02105722, 0.02105722, 0.02105722, 0.02105722, 0.02105722,
        0.02105722, 0.02105722, 0.02105722, 0.02105722, 0.02105722,
        0.02105722, 0.02105722, 0.02105722, 0.02105722, 0.02105722,
        0.03136798, 0.02105722, 0.02105722, 0.02105722, 0.02105722,
        0.02105722, 0.02105722, 0.02105722, 0.02105722, 0.02105722,
        0.02105722, 0.02105722, 0.02105722, 0.02105722, 0.02105722,
        0.02105722, 0.02105722, 0.02105722, 0.02105722, 0.02105722,
        0.02105722, 0.02105722],
       [0.0212766 , 0.0212766 , 0.0212766 , 0.0212766 , 0.0212766 ,
        0.0212766 , 0.0212766 , 0.0212766 , 0.0212766 , 0.0212766 ,
        0.0212766 , 0.0212766 , 0.0212766 , 0.0212766 , 0.0212766 ,
        0.0212766 , 0.0212766 , 0.0212766 , 0.0212766 , 0.0212766 ,
        0.0212766 , 0.0212766 , 0.0212766 , 0.0212766 , 0.0212766 ,
        0.02127

In [12]:
# トピック分布 theta_tdk の中身
for t in range(10):
    print(np.array(cttm.theta_tdk[t]))

[[0.26665309 0.20342501 0.14741845 0.18933311 0.19317034]
 [0.26665309 0.20342501 0.14741845 0.22473843 0.15776502]
 [0.21911607 0.22759974 0.1253246  0.17222033 0.25573926]]
[[0.25647469 0.23189172 0.36291689 0.07361239 0.0751043 ]
 [0.25313611 0.64706912 0.02776181 0.04232269 0.02971027]
 [0.13440221 0.26847808 0.07687206 0.36338138 0.15686628]]
[[0.2        0.2        0.2        0.2        0.2       ]
 [0.0704266  0.9012399  0.00788207 0.01201616 0.00843527]
 [0.12383253 0.27357843 0.07082667 0.2943814  0.23738096]]
[[0.24137491 0.22395987 0.3236164  0.10499596 0.10605286]
 [0.16746004 0.62122599 0.02585413 0.15779113 0.02766871]
 [0.11857641 0.27611476 0.06782041 0.29770179 0.23978664]]
[[0.34816602 0.33943354 0.17435786 0.06875631 0.06928627]
 [0.09996782 0.81180357 0.01348799 0.06030598 0.01443464]
 [0.09677917 0.36453819 0.05535336 0.32454261 0.15878667]]
[[0.31712927 0.31328408 0.15480284 0.10727522 0.10750858]
 [0.06041621 0.82324344 0.00843967 0.09886867 0.00903201]
 [0.26298

In [13]:
for t in range(10):
    print(np.array(cttm.phi_tkv[t][2]))

[0.30140391 0.19859609 0.30140391 0.19859609]
[0.20748266 0.13671105 0.36328895 0.29251734]
[0.21307461 0.32406907 0.26776766 0.19508866]
[0.30440732 0.17618617 0.34658362 0.17282289]
[0.195064   0.30399427 0.33495447 0.16598726]
[0.286973   0.22202415 0.24247928 0.24852356]
[0.27064159 0.30006309 0.2016827  0.22761262]
[0.20733463 0.38381734 0.23212232 0.17672571]
[0.29043091 0.18908586 0.2578242  0.26265903]
[0.34449705 0.22154917 0.21602683 0.21792695]
