## TTM デバッグ

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import sys
sys.path.append('../')
from cython_folder.TTM.ttm import TTM

In [2]:
# 人工データ
N_tdv = [
    [
        [1, 2, 1, 2],
        [3, 2, 0, 1],
        [0, 2, 1, 0]
    ],
    [
        [1, 1, 1, 1],
        [3, 2, 1, 2],
        [0, 2, 1, 0]
    ],
    [
        [0, 0, 0, 0],
        [3, 2, 0, 1],
        [0, 2, 1, 0]
    ],
    [
        [1, 1, 1, 1],
        [3, 2, 1, 2],
        [0, 2, 1, 0]
    ],
    [
        [1, 2, 1, 2],
        [3, 2, 0, 1],
        [0, 2, 1, 0]
    ],
    [
        [1, 1, 1, 1],
        [3, 2, 1, 2],
        [0, 2, 1, 0]
    ],
    [
        [1, 2, 1, 2],
        [3, 2, 0, 1],
        [0, 2, 1, 0]
    ],
    [
        [1, 1, 1, 1],
        [3, 2, 1, 2],
        [0, 2, 1, 0]
    ],
    [
        [1, 2, 1, 2],
        [3, 2, 0, 1],
        [0, 2, 1, 0]
    ],
    [
        [1, 1, 1, 1],
        [3, 2, 1, 2],
        [0, 2, 1, 0]
    ]
]

In [3]:
# 学習
# k: トピック数, L: 依存時間数, N: 時刻毎のBOW行列
ttm = TTM(K=5, L=3, V=4, N_tdv=N_tdv)
# ttm_estimateの引数: 反復数
ttm.ttm_estimate(10)

100%|██████████| 10/10 [00:00<00:00, 693.64it/s]


In [5]:
# ハイパーパラメータ alpha の中身
print(np.array(ttm.alpha_tdl))

[[[2.         2.         2.        ]
  [2.         2.         2.        ]
  [2.         2.         2.        ]]

 [[2.81084615 2.         2.        ]
  [2.37713966 2.         2.        ]
  [3.15520549 2.         2.        ]]

 [[2.         2.         2.        ]
  [3.10809658 3.15057828 2.        ]
  [1.23145224 1.30612766 2.        ]]

 [[6.09923928 0.         0.        ]
  [2.55724486 2.27035865 2.29702411]
  [2.62322763 2.21685807 2.53717475]]

 [[4.60044582 7.04320165 0.17576075]
  [3.20989406 1.77877405 1.14050253]
  [1.59274408 1.54463853 1.5246075 ]]

 [[2.6851161  1.62783876 2.43908523]
  [2.25926695 2.20426676 2.26410075]
  [1.98369768 2.60912755 2.65302108]]

 [[2.52246556 3.06802344 4.78837533]
  [2.30290559 2.53659324 2.54809075]
  [2.68363794 1.7431451  2.96452078]]

 [[2.6527227  2.1778291  2.3159543 ]
  [2.58708489 2.88535147 2.22978017]
  [1.34873719 1.67669024 2.09291271]]

 [[2.20119796 4.37540667 4.27593028]
  [1.91027332 1.76336669 1.88266065]
  [2.9525077  1.827478

In [6]:
# 単語分布 phi_tkv の中身
print(np.array(ttm.phi_tkv))

[[[0.25       0.25       0.25       0.25      ]
  [0.23872263 0.2838321  0.23872263 0.23872263]
  [0.25       0.25       0.25       0.25      ]
  [0.27608474 0.32825423 0.17174577 0.22391526]
  [0.25       0.25       0.25       0.25      ]]

 [[0.25       0.25       0.25       0.25      ]
  [0.2439593  0.32616608 0.18591532 0.2439593 ]
  [0.25       0.25       0.25       0.25      ]
  [0.2812596  0.30539355 0.2329917  0.18035516]
  [0.25       0.25       0.25       0.25      ]]

 [[0.25       0.25       0.25       0.25      ]
  [0.1615657  0.45509993 0.13881755 0.24451683]
  [0.25       0.25       0.25       0.25      ]
  [0.38958873 0.27693848 0.20026551 0.13320728]
  [0.25       0.25       0.25       0.25      ]]

 [[0.21649485 0.21649485 0.35051546 0.21649485]
  [0.16487594 0.43201889 0.14289908 0.2602061 ]
  [0.19918644 0.19918644 0.30081356 0.30081356]
  [0.35275354 0.30231982 0.20006098 0.14486566]
  [0.19090909 0.30909091 0.30909091 0.19090909]]

 [[0.21424052 0.33370992 0.23780

In [7]:
# トピック分布 theta_tdk の中身
for t in range(10):
    print(np.array(ttm.theta_tdk[t]))

[[0.         0.75708393 0.         0.24291607 0.        ]
 [0.         0.49048493 0.         0.50951507 0.        ]
 [0.         0.52976036 0.         0.47023964 0.        ]]
[[0.         0.75292355 0.         0.24707645 0.        ]
 [0.         0.49782034 0.         0.50217966 0.        ]
 [0.         0.43402333 0.         0.56597667 0.        ]]
[[0.2        0.2        0.2        0.2        0.2       ]
 [0.         0.41542703 0.         0.58457297 0.        ]
 [0.         0.58263966 0.         0.41736034 0.        ]]
[[0.12078611 0.21980347 0.31882083 0.21980347 0.12078611]
 [0.         0.28557629 0.         0.71442371 0.        ]
 [0.         0.46588974 0.         0.53411026 0.        ]]
[[0.1663529  0.1432241  0.27359822 0.25047188 0.1663529 ]
 [0.         0.34820071 0.         0.65179929 0.        ]
 [0.         0.30066941 0.         0.69933059 0.        ]]
[[0.19820557 0.20742064 0.25497012 0.14119811 0.19820557]
 [0.         0.49951901 0.         0.50048099 0.        ]
 [0.     

In [8]:
for t in range(10):
    print(np.array(ttm.phi_tkv[t][2]))

[0.25 0.25 0.25 0.25]
[0.25 0.25 0.25 0.25]
[0.25 0.25 0.25 0.25]
[0.19918644 0.19918644 0.30081356 0.30081356]
[0.17654798 0.17654798 0.22193286 0.42497118]
[0.17368322 0.17368322 0.21885633 0.43377723]
[0.15008001 0.15008001 0.20114054 0.49869944]
[0.19408601 0.19408601 0.22584828 0.38597971]
[0.15256851 0.25959142 0.19136533 0.39647474]
[0.14749553 0.17492466 0.18286511 0.4947147 ]
